### ISSUE TITLE
/users/search api needs to accept general any input. 

### ISSUE THREAD

**Issue by tboydston** [blshao84/puluo_document#13]
/users/search api needs to accept general any input. The search is a single field. We can't extrapolate whether the input is an email, name, or phone number on the front end.

**Comment by tboydston** [comment]
You should also have a parameter to just search your existing friends.

**Comment by blshao84** [comment]
the new api accepts one single parameter, 'keyword', and will match users with last_name or first_name or email or mobile

**Comment by tboydston** [comment]
You should probably make this case insensative.
