### ISSUE TITLE
Add parameter to event list api to return only events the user is registered for. 

### ISSUE THREAD

**Issue by tboydston** [blshao84/puluo_document#17]
Add parameter to event list api to return only events the user is registered for.

**Comment by sinorockie** [comment]
@blshao84 RegisteredEventSearchAPI

**Comment by blshao84** [comment]
API:
/events/registered
Param:
token:String, 

Desc:
Get list of already registered events of this login user

Results: same as event search result

{"token":"eyzhm5yp98kk101wqqc9rtksv","events":[{"phone":"123456789","status":"Open","city":"北京","event_uuid":"event_detail_event_1","thumbnail":["http://upyun.com/puluo/xyz.jpg"],"details":"详细信息","address":"北京市国贸大厦250号","likes":0,"geo_location":{"longitude":1234.567,"latitude":7654.321},"coach_uuid":"123456","images":["http://upyun.com/puluo/xyz.jpg"],"event_time":1433136600000,"capacity":15,"registered_users":3,"event_name":"臀部炸弹","coach_name":"Jerry Ass"}]}
