### ISSUE TITLE
User settings API need to return human readable name for each setting. 

### ISSUE THREAD

**Issue by tboydston** [blshao84/puluo_document#18]
User settings API need to return human readable name for each setting. This name should be in an array with a language prefix in case you want to implement multiple languages later.

**Comment by blshao84** [comment]
/users/setting returns new setting format. Each setting contains a name and it's value.

{"user_uuid":"xxxxxx",
  "auto_add_friend": {"name":"允许自动添加好友","value":true},
  "allow_stranger_view_timeline":{"name":"允许陌生人浏览","value":true},
  "allow_searched":{"name":"允许被搜索到","value":true}
}

We still have the old api: /users/privacy which returns the old format. Will keep both for a while
