### ISSUE TITLE
user API needs to return the status of pending friendship requests to the user 

### ISSUE THREAD

**Issue by tboydston** [blshao84/puluo_document#20]
user API needs to return the status of any pending friendship requests to the user. 
Suggested parameters:  
request_status: none, pending, denied, following 

This could also be built into the "following" response.

**Comment by blshao84** [comment]
same issue ?https://github.com/blshao84/puluo_document/issues/14

**Comment by sinorockie** [comment]
@blshao84 I will complete the test later.
