### ISSUE TITLE
Event keyword search does not filter search results. 

### ISSUE THREAD

**Issue by tboydston** [blshao84/puluo_document#21]
Event keyword search does not filter search results. The same results are returned whether a keyword parameter is added or not.

**Comment by blshao84** [comment]
do you have a sample request?

**Comment by tboydston** [comment]
You can test this on the event search on the live site. My test parameters were. 

city: "Beijing"
keywords: "test"
sort_direction: "Desc"
token: "sj5nj18ptdt"

**Comment by blshao84** [comment]
parameter name is 'keyword', no 's'.
