### ISSUE TITLE
User page - Fix broken pending friend request status 

### ISSUE THREAD

**Issue by tboydston** [blshao84/puluo_document#35]
User page - Fix broken pending friend request status

**Comment by sinorockie** [comment]
@tboydston 
Send a friend request from you to Baolin:
{"token":"1psyokoxu3f8r18m2u1g866yg1","friend_request":{"updated_at":1430648544016,"request_id":"3f9b4c91-fbd4-4ac1-b926-6c44ccf6edbc","status":"Requested","created_at":1430648544016,"messages":[{"content":"用户:Tracey Boydston向您提出好友申请","from_user_thumbnail":"","from_user_last_name":"Boydston","to_user_thumbnail":"","to_user_last_name":"Shao","from_user":"1c3c26e3-e468-4d4e-834e-69ca4ab47e11","msg_id":"08385e33-b0b0-4156-a32c-da169ae0dd85","created_at":1430648544000,"to_user":"beac0ed2-e5aa-42db-bfa2-1855b1679366","to_user_first_name":"Baolin","from_user_first_name":"Tracey"}]}}
-------------------------------------------------------------------------------------------------------------------------------
Send the second friend request from you to Baolin after the last one was denied,
{"token":"ys05k2z9qtpnwmuwimp3bflw","friend_request":{"updated_at":1430648952061,"request_id":"c74e46c3-ebe2-43d1-8d16-ed583c949599","status":"Requested","created_at":1430648952061,"messages":[{"content":"用户:Tracey Boydston向您提出好友申请","from_user_thumbnail":"","from_user_last_name":"Boydston","to_user_thumbnail":"","to_user_last_name":"Shao","from_user":"1c3c26e3-e468-4d4e-834e-69ca4ab47e11","msg_id":"40594a14-522d-4553-afa5-821c082644c9","created_at":1430648952000,"to_user":"beac0ed2-e5aa-42db-bfa2-1855b1679366","to_user_first_name":"Baolin","from_user_first_name":"Tracey"},{"content":"用户:Tracey Boydston向您提出好友申请","from_user_thumbnail":"","from_user_last_name":"Boydston","to_user_thumbnail":"","to_user_last_name":"Shao","from_user":"1c3c26e3-e468-4d4e-834e-69ca4ab47e11","msg_id":"08385e33-b0b0-4156-a32c-da169ae0dd85","created_at":1430648544000,"to_user":"beac0ed2-e5aa-42db-bfa2-1855b1679366","to_user_first_name":"Baolin","from_user_first_name":"Tracey"}]}}

**Comment by sinorockie** [comment]
@tboydston 
Send a friend request from you to Baolin:
{"token":"1psyokoxu3f8r18m2u1g866yg1","friend_request":{"updated_at":1430648544016,"request_id":"3f9b4c91-fbd4-4ac1-b926-6c44ccf6edbc","status":"Requested","created_at":1430648544016,"messages":[{"content":"用户:Tracey Boydston向您提出好友申请","from_user_thumbnail":"","from_user_last_name":"Boydston","to_user_thumbnail":"","to_user_last_name":"Shao","from_user":"1c3c26e3-e468-4d4e-834e-69ca4ab47e11","msg_id":"08385e33-b0b0-4156-a32c-da169ae0dd85","created_at":1430648544000,"to_user":"beac0ed2-e5aa-42db-bfa2-1855b1679366","to_user_first_name":"Baolin","from_user_first_name":"Tracey"}]}}
-------------------------------------------------------------------------------------------------------------------------------
Send the second friend request from you to Baolin after the last one was denied,
{"token":"ys05k2z9qtpnwmuwimp3bflw","friend_request":{"updated_at":1430648952061,"request_id":"c74e46c3-ebe2-43d1-8d16-ed583c949599","status":"Requested","created_at":1430648952061,"messages":[{"content":"用户:Tracey Boydston向您提出好友申请","from_user_thumbnail":"","from_user_last_name":"Boydston","to_user_thumbnail":"","to_user_last_name":"Shao","from_user":"1c3c26e3-e468-4d4e-834e-69ca4ab47e11","msg_id":"40594a14-522d-4553-afa5-821c082644c9","created_at":1430648952000,"to_user":"beac0ed2-e5aa-42db-bfa2-1855b1679366","to_user_first_name":"Baolin","from_user_first_name":"Tracey"},{"content":"用户:Tracey Boydston向您提出好友申请","from_user_thumbnail":"","from_user_last_name":"Boydston","to_user_thumbnail":"","to_user_last_name":"Shao","from_user":"1c3c26e3-e468-4d4e-834e-69ca4ab47e11","msg_id":"08385e33-b0b0-4156-a32c-da169ae0dd85","created_at":1430648544000,"to_user":"beac0ed2-e5aa-42db-bfa2-1855b1679366","to_user_first_name":"Baolin","from_user_first_name":"Tracey"}]}}

**Comment by blshao84** [comment]
user A sends a user profile req on user B, the 'following' field in the result:
'true' - if A and B are friends
'fale' - if A and B are not friends and A/B don't have a pending req
'pending' - if A and B are not friends but A/B have a pending req (the pending req could be from A to B or B to A)
