### ISSUE TITLE
event detail page image gallery layout

### ISSUE THREAD

**Issue by blshao84** [blshao84/puluo_document#56]
For the event detail page, this time I see the image gallery looks much better and image size is much sensible. But can we add some space on both sides of the gallery also with some arrows, otherwise user might not event know there are multiple images and they could slide.
![a4d3f75f5e053bb1b2cfe21207b270a9](https://cloud.githubusercontent.com/assets/3524805/7900090/c4eb500e-0776-11e5-931d-7e11172ae2a1.jpg)

**Comment by tboydston** [comment]
Added footer pagination. This is better for swipe interactions then arrows.
