### ISSUE TITLE
Add price to event discovery and event detail page

### ISSUE THREAD

**Issue by blshao84** [blshao84/puluo_document#58]
For the discovery page, can we add price to each event like this：
![41e6cd84699f72fdb015de207cc45209](https://cloud.githubusercontent.com/assets/3524805/7900094/098f7f50-0777-11e5-92c7-6894f36cce7a.jpg)

**Comment by tboydston** [comment]
@blshao84 You need to add the price to the event search API

**Comment by blshao84** [comment]
updated the dev server!
