### ISSUE TITLE
user profile page layout and error msg

### ISSUE THREAD

**Issue by blshao84** [blshao84/puluo_document#63]
In the personal profile page, the format of birthday info's default value is set as yyyy-mm-dd hh:mm:ss. We should use yyyy-mm-dd instead of the current one. Also, the error msg still shows up even though I have already provided the name and email information
![img_1989_recompress](https://cloud.githubusercontent.com/assets/3524805/7900113/982fc3dc-0777-11e5-990a-a30c20cc8cdf.jpg)

**Comment by tboydston** [comment]
@blshao84 The birthday field is filled through the API. If you would like to have something different don't return a birthday by default.
