### ISSUE TITLE
Pending request page issue

### ISSUE THREAD

**Issue by blshao84** [blshao84/puluo_document#65]
When I try to follow some one, I can see the request is pending. Then I click the request and type some words, I can see the below weird page. If I go outside this page and come back again, the message page looks normal, however, the request .

(1) Pending request (The message content needs to be changed @Baolin)

![12_recompress](https://cloud.githubusercontent.com/assets/3524805/7900134/5e7f3a04-0778-11e5-9261-98a66510785a.jpg)

(2) Weird page

![13_recompress](https://cloud.githubusercontent.com/assets/3524805/7900135/639cf4b8-0778-11e5-8790-f6edaf414b2d.jpg)

(3) Go outside then come back, then pending status disappeared and the message page looks normal.

![img_1986_recompress](https://cloud.githubusercontent.com/assets/3524805/7900140/84931fee-0778-11e5-9781-f02283b54a7f.jpg)

**Comment by tboydston** [comment]
I think this is resolved but it is difficult to test as I do not know anyone else on the platform to send a friend request to. Let me know if it persists.
