### ISSUE TITLE
Event API response needs to include class price and array of class attendees

### ISSUE THREAD

**Issue by tboydston** [blshao84/puluo_document#8]
Event API response needs to include class price and array of class attendees

Array should include name, UUID, and thumbnail.

**Comment by blshao84** [comment]
@sinorockie 
for class price, it's already in event table so let's just add it to the json.
for list of attendees, we need:
1. given event uuid, get the list of payment orders that are paid or complete
2. get users out of those payment orders
3. add those users to event result and return user's uuid, name and thumbnail,
